#!/usr/bin/env bash

set -euo pipefail
source "$BASE_DIR/framework.sh"

# Check if module is enabled
if [ ! "$MOD_BANNER_RUN" = "true" ]; then
    exit 0
fi

hostname=${HOSTNAME:-$(hostname)}
if [ "$MOD_BANNER_PRINT" = "HOSTNAME" ]; then
    print_columns "" "${CA}$(figlet -f ${MOD_BANNER_FONT} ${hostname%%.*})${CN}"
else
    print_columns "" "${CA}$(figlet -f ${MOD_BANNER_FONT} $hostname)${CN}"
fi

