#!/usr/bin/env bash

set -euo pipefail
source "$BASE_DIR/framework.sh"

hostname=${HOSTNAME:-$(hostname)}

if [ "$BANNER" = "HOSTNAME" ]; then
    print_columns "" "${CA}$(figlet ${hostname%%.*})${CN}"
else
    print_columns "" "${CA}$(figlet $hostname)${CN}"
fi
