#!/usr/bin/env bash

set -euo pipefail
source "$BASE_DIR/framework.sh"

# Check if module is enabled
[[ -z "{$MOD_USER_RUN+x}" ]] && exit 0
[[ ! "$MOD_USER_RUN" = "true" ]] && exit 0

user=${USER:-$(id -un)}
hostname=${HOSTNAME:-$(hostname)}

user_Log () {
    echo "${user}@${hostname}"
    if [ "$MOD_USER_LAST" = "true" ]; then
            while read -r login lipaddr lday lmonth ldate ltime; do
            echo "$(print_split "${WIDTH}" "${login}" "${lipaddr} ${lday} ${lmonth} ${ldate} ${ltime}")"
            done <<< "$(last -i -n 5 --time-format short | head -5 | awk '($1 != "reboot") {print $1,$3,$4,$5,$6,$7}')"

            echo -e "Last successfull logins:\n------------------------"
            # print_split "${WIDTH}" "${login}" "${lipaddr} ${lday} ${lmonth} ${ldate} ${ltime}"
            # last -i -n 5 --time-format short | head -5 | awk '($1 != "reboot") {print $1,$3,$4,$5,$6,$7}'
    fi
}

out="$(user_Log)"
print_columns "Logged as" "$out"
