#!/usr/bin/env bash

set -euo pipefail
source "$BASE_DIR/framework.sh"

# Check if module is enabled
if [ ! "$MOD_OS_RUN" = "true" ]; then
    exit 0
fi

get_os

# source "/etc/os-release"

print_columns "OS" "$os $arch"
