#!/usr/bin/env bash

set -euo pipefail
source "$BASE_DIR/framework.sh"

# Check if module is enabled
[[ -z "${MOD_IP_RUN+x}" ]] && exit 0
[[ ! "$MOD_IP_RUN" = "true" ]] && exit 0

case $os in
    Linux*)
        ips_v4="$(ip a | awk '/inet / && /global/ {split($2, arr, /\//); print arr[1]}')"
    ;;

    FreeBSD)
        ips_v4="$(ifconfig | awk '/inet/ && /broadcast/ {split($2, arr, /\//); print arr[1]}')"
    ;;

    SunOS)
        ips_v4="$(ifconfig | awk '/inet/ && /broadcast/ {split($2, arr, /\//); print arr[1]}')"
    ;;
esac

IFS=$'\n' read -r -a ips <<< $ips_v4
out="$(print_wrap $WIDTH "${ips[@]}")"

print_columns "IP addresses" "$out"
