#!/usr/bin/env bash

set -euo pipefail
source "$BASE_DIR/framework.sh"

# Check if module is enabled
[[ -z "${MOD_PUBLIC_IP_RUN=x}" ]] && exit 0
[[ ! "$MOD_PUBLIC_IP_RUN" = "true" ]] && exit 0

ip_v4="$(curl --silent http://ifconfig.me/ip)"

out="$(print_wrap $WIDTH "${ip_v4}")"

print_columns "Public IP address" "$out"
