#!/usr/bin/env bash

set -euo pipefail
source "$BASE_DIR/framework.sh"

# Check if module is enabled
if [ ! "$MOD_UPTIME_RUN" = "true" ]; then
    exit 0
fi

get_os
case $os in
    Linux*)
        IFS=. read -r s _ < /proc/uptime
    ;;

    *BSD*)
        s=$(sysctl -n kern.boottime)
        s=${s#*=}
        s=${s%,*}
        s=$(($(date +%s) - s))
    ;;

    SunOS)
        IFS='	.' read -r _ s _ <<-EOF
            $(kstat -p unix:0:system_misc:snaptime)
EOF
    ;;
esac

# Get days, hours and minutes.
d=$((s / 60 / 60 / 24))
h=$((s / 60 / 60 % 24))
m=$((s / 60 % 60))






# uptime=$(uptime -p | cut -d ' ' -f 2-)

# print_columns "Uptime" "$uptime"
print_columns "Uptime" "${d}d ${h}h ${m}m"
