#!/usr/bin/env bash

set -euo pipefail
source "$BASE_DIR/framework.sh"

# Check if module is enabled
if [ ! "$MOD_LOAD_RUN" = "true" ]; then
    exit 0
fi

get_os
if [ "$os" == "FreeBSD" ]; then
    ftext="load averages:"
    nproc="$(sysctl -n hw.ncpu)"
elif [ "$os" == "Linux" ]; then
    ftext="load average:"
    nproc="$(nproc)"
elif [ "$os" == "SunOS" ]; then
    ftext="load average:"
    nproc="$(psrinfo -p)"
fi




# loads="$(cat /proc/loadavg | cut -d ' ' -f '1,2,3')"
loads="$(uptime | awk -F "$ftext" '{print $2}' | cut -d ',' -f '1,2,3' | sed 's/,//g; s/^ //g')"
# nproc=$(nproc)
warning_threshold=$(bc -l <<< "$nproc * 0.9")
error_threshold=$(bc -l <<< "$nproc * 1.5")

text=""
for load in $loads; do
    text+="$(print_color $load $load $warning_threshold $error_threshold), "
done

print_columns "Load average" "${text::-2}"
