#!/usr/bin/env bash

set -euo pipefail
source "$BASE_DIR/framework.sh"

# Check if module is enabled
[[ -z "${MOD_SERVICES_LINUX_RUN+x}" ]] && exit 0
[[ ! "$MOD_SERVICES_LINUX_RUN" = "true" ]] && exit 0

statuses=()
for key in "${!services[@]}"; do
    # systemctl is-active returns non-zero code if service is inactive
    set +e; status=$(systemctl is-active ${services[$key]}); set -e
    statuses+=("$(print_status "$key" "$status")")
done

out="$(print_wrap $WIDTH "${statuses[@]}")"

print_columns "Services" "$out"
