#!/usr/bin/env bash

set -euo pipefail
source "$BASE_DIR/framework.sh"

# Check if module is enabled
if [ ! "$MOD_SERVICES_LINUX_RUN" = "true" ]; then
    exit 0
fi

statuses=()
for key in "${!services[@]}"; do
    # systemctl is-active returns non-zero code if service is inactive
    set +e; status=$(systemctl is-active ${services[$key]}); set -e
    statuses+=("$(print_status "$key" "$status")")
done

text="$(print_wrap $WIDTH "${statuses[@]}")"

print_columns "Services" "$text"
