#!/usr/bin/env bash

#======== CERT: Check validity of certificates ================================

set -euo pipefail
source "$BASE_DIR/framework.sh"

# Check if module is enabled
[[ -z "${MOD_CERT_RUN+x}" ]] && exit 0
[[ ! "$MOD_CERT_RUN" = "true" ]] && exit 0

out=""

cert_validity () {
    currentTime=$(date +%s)
    for sslcheck in ${!certhostlist[@]}; do
        IFS=";" read -r shortname fqdn port <<< ${certhostlist[$sslcheck]}
        certTime=$(openssl s_client -servername ${fqdn} -connect ${fqdn}:${port} < /dev/null 2>/dev/null | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f2)
        certLineTime=$(date -d "${certTime}" +"%a %b %d %Y")
        certTimestamp=$(date -d "${certTime}" +%s)
        if [ "${certTimestamp}" -ge "${currentTime}" ]; then
            sign="${CO}●${CN}"
        else
            sign="${CE}●${CN}"
        fi
        echo "$(print_split "$(( $WIDTH + 11 ))" "${sign}${shortname}" "$certLineTime")"
    done
}

# Call function validity and put output into variable.
out="$(cert_validity)"

# Call function "print_columns" from framewark.sh.
print_columns "Certificate Validity" "$out"
