#!/usr/bin/env bash

set -eu
source "$BASE_DIR/framework.sh"

# Check if module is enabled
[[ -z "${MOD_UPDATES_RUN+x}" ]] && exit 00
[[ ! "$MOD_UPDATES_RUN" = "true" ]] && exit 00

if type checkupdates >/dev/null 2>&1; then
    updates=$(checkupdates 2> /dev/null | wc -l )
    if type yay >/dev/null 2>&1; then
        updates_aur=$(yay -Qum 2> /dev/null | wc -l)
        updates=$(($updates + $updates_aur))
    fi
elif type dnf >/dev/null 2>&1; then
    updates=$(dnf check-update --quiet | grep -v "^$" | wc -l)
elif type apt >/dev/null 2>&1; then
    updates=$(apt list --upgradable 2>/dev/null | grep upgradable | wc -l)
else
    updates="N/A"
fi

out="$(print_color "$updates available" $updates 1 50)"

print_columns "Updates" "$out"
