#!/usr/bin/env bash

set -euo pipefail
source "$BASE_DIR/framework.sh"

# Check if module is enabled
if [ ! "$MOD_QUOTE_RUN" = "true" ]; then
    exit 0
fi

quote="$(fortune -s | fold -sw $WIDTH)"

print_columns "Quote" "$quote"
