#!/usr/bin/env bash

set -euo pipefail
source "$BASE_DIR/framework.sh"

# Check if module is enabled
[[ -z "${MOD_QUOTE_RUN+x}" ]] && exit 0
[[ ! "$MOD_QUOTE_RUN" = "true" ]] && exit 0

out="$(fortune -s | fold -sw $WIDTH)"

print_columns "Quote" "$out"
